version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/masonry-ai-frontend
    overwrite: true
permissions:
  - object: /var/www/masonry-ai-frontend
    pattern: "**"
    owner: nodejs
    group: nodejs
    mode: 755
    type:
      - directory
  - object: /var/www/masonry-ai-frontend
    pattern: "**"
    owner: nodejs
    group: nodejs
    mode: 644
    type:
      - file
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 300
      runas: root 